#!/bin/sh

cat > "$AUTOPKGTEST_TMP"/smoketest.py <<EOF
def foo():
    return 'yes'

def test_foo():
    assert foo() == 'yes'

EOF

cd "$AUTOPKGTEST_TMP"

for py in $(py3versions -s); do
    TMPDIR="$AUTOPKGTEST_TMP" $py -m pytest smoketest.py
done
